In [1]:
import os
import time
import tensorflow as tf
import scipy.io as sio 
from keras.applications.resnet50 import ResNet50
from keras.applications.mobilenet import MobileNet
import keras


c:\Users\USER\anaconda3\envs\MNIST\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\Users\USER\anaconda3\envs\MNIST\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\Users\USER\anaconda3\envs\MNIST\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\Users\USER\anaconda3\envs\MNIST\lib\site-packages\tensorflow\python\frame

In [2]:

def one_hot_matrix(labels, C):
    
    ### START CODE HERE ###
    
    # Create a tf.constant equal to C (depth), name it 'C'.
    depth = tf.constant(C, name = "C")
    
    # Use tf.one_hot, be careful with the axis (approx. 1 line)
    one_hot_matrix = tf.one_hot(labels, depth, axis=0)
    
    # Create the session
    sess = tf.Session()
    
    # Run the session
    one_hot = sess.run(one_hot_matrix)
    
    # Close the session.
    sess.close() 
    
    return one_hot

In [4]:
from sklearn.utils import shuffle
file_path = os.getcwd() + '\\train'
label_name = os.listdir(file_path)
class_num = 3

matfn='train_messy_mid.mat' 
data=sio.loadmat(matfn) 


X_train = data['X_data'] 
X_train = X_train / 255
Y_train = data['Y_data']
# Y_train = Y_train.T

# X_train, Y_train = shuffle(X_train, Y_train)



"""
X_val = X_train[4200:]
Y_val = Y_train[4200:]

X_train = X_train[:4200]
Y_train = Y_train[:4200]
"""

print(X_train.shape)
print(Y_train.shape)

(2320, 128, 128, 3)
(1, 2320)


In [6]:
from sklearn.utils import shuffle
file_path = os.getcwd() + '\\train'
label_name = os.listdir(file_path)
class_num = 3

matfn_valid='valid_messy_mid.mat' 
data=sio.loadmat(matfn_valid) 


X_valid = data['X_data'] 
X_valid = X_valid / 255
Y_valid = data['Y_data']
# Y_train = Y_train.T

# X_train, Y_train = shuffle(X_train, Y_train)



"""
X_val = X_train[4200:]
Y_val = Y_train[4200:]

X_train = X_train[:4200]
Y_train = Y_train[:4200]
"""

print(X_valid.shape)
print(Y_valid.shape)

(93, 128, 128, 3)
(1, 93)


In [5]:
data_num = X_train.shape[0] 
Y_train = one_hot_matrix(Y_train, class_num)
Y_train = Y_train.T
Y_train = Y_train.reshape(data_num, class_num)
print(Y_train.shape)

(2320, 3)


In [7]:
valid_num = X_valid.shape[0] 
Y_valid = one_hot_matrix(Y_valid, class_num)
Y_valid = Y_valid.T
Y_valid = Y_valid.reshape(valid_num, class_num)
print(Y_valid.shape)

(93, 3)


In [8]:
print(Y_train)
print(Y_train.shape)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 ...
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
(2320, 3)


In [9]:
import random
num_examples = X_train.shape[0]
index_list = list(range(num_examples))
random.shuffle(index_list)

# 根据打乱后的索引重新排列训练数据和标签
X_train = X_train[index_list]
Y_train = Y_train[index_list]

In [10]:
import random
num_examples = X_valid.shape[0]
index_list = list(range(num_examples))
random.shuffle(index_list)

# 根据打乱后的索引重新排列训练数据和标签
X_valid = X_valid[index_list]
Y_valid = Y_valid[index_list]

In [11]:
print(Y_train[0:200])
print(Y_train.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0.

In [12]:
print(Y_valid)
print(Y_valid.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0.

In [12]:
from keras.callbacks import EarlyStopping,ModelCheckpoint,ReduceLROnPlateau

# early_stopping : val_loss 連續不降低時，結束訓練
early_stopping = EarlyStopping(monitor='val_loss', patience=15, verbose=1,restore_best_weights=True,mode='auto')
# reduce_lr : val_loss 連續不降低時，減少learning rate
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, verbose=1, mode='auto',
                            epsilon=0.0001, cooldown=0, min_lr=0)

checkpoint = ModelCheckpoint('ResNet50_messy_v1.h5', monitor='val_loss', verbose=1,
    save_best_only=True, mode='auto', period=1)

pre_model = MobileNet(input_shape = (224, 224, 3), weights='imagenet')
transfer_model = keras.models.Sequential()
transfer_model.add(pre_model)
# transfer_model.add(keras.layers.Flatten())
transfer_model.add(keras.layers.Dense(1024, activation='relu'))
transfer_model.add(keras.layers.Dense(512, activation='relu'))
transfer_model.add(keras.layers.Dropout(0.5))
transfer_model.add(keras.layers.Dense(256, activation='relu'))
transfer_model.add(keras.layers.Dense(128, activation='relu'))
transfer_model.add(keras.layers.Dropout(0.5))
transfer_model.add(keras.layers.Dense(64, activation='relu'))
transfer_model.add(keras.layers.Dense(3, activation='softmax'))

transfer_model.summary()

Instructions for updating:
Colocations handled automatically by placer.


c:\Users\USER\anaconda3\envs\MNIST\lib\site-packages\keras\callbacks.py:1065: UserWarning: `epsilon` argument is deprecated and will be removed, use `min_delta` instead.
  warnings.warn('`epsilon` argument is deprecated and '


Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
17227776/17225924 [==============================] - 4s 0us/step
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
mobilenet_1.00_224 (Model)   (None, 1000)              4253864   
_________________________________________________________________
dense_1 (Dense)              (None, 1024)              1025024   
_________________________________________________________________
dense_2 (Dense)              (None, 512)               524800    
_________________________________________________________________
dropout_1 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 256)               131328    
_________________________________________________________________
dense_4 (Dense)             

In [13]:
optimizer = keras.optimizers.Adam(lr=0.0001)
transfer_model.compile(optimizer=optimizer, loss="categorical_crossentropy", metrics=["accuracy"])
history = transfer_model.fit(x=X_train, y=Y_train, validation_data=(X_valid, Y_valid), epochs=50, batch_size = 32, callbacks=[early_stopping,checkpoint,reduce_lr])
        
# complete_time=time.strftime("%Y_%m_%d %H_%M_%S", time.localtime()) 
# model.save('MobileNet_'+str(complete_time)+'.h5')

Instructions for updating:
Use tf.cast instead.
Train on 2320 samples, validate on 93 samples
Epoch 1/50
2320/2320 [==============================] - 705s 304ms/step - loss: 1.0983 - acc: 0.3504 - val_loss: 1.0959 - val_acc: 0.4301

Epoch 00001: val_loss improved from inf to 1.09593, saving model to ResNet50_messy_v1.h5
Epoch 2/50
2320/2320 [==============================] - 716s 309ms/step - loss: 1.0212 - acc: 0.5164 - val_loss: 0.7974 - val_acc: 0.6344

Epoch 00002: val_loss improved from 1.09593 to 0.79742, saving model to ResNet50_messy_v1.h5
Epoch 3/50
2320/2320 [==============================] - 731s 315ms/step - loss: 0.5038 - acc: 0.7909 - val_loss: 0.4410 - val_acc: 0.8387

Epoch 00003: val_loss improved from 0.79742 to 0.44097, saving model to ResNet50_messy_v1.h5
Epoch 4/50
2320/2320 [==============================] - 708s 305ms/step - loss: 0.2587 - acc: 0.9310 - val_loss: 0.3432 - val_acc: 0.8817

Epoch 00004: val_loss improved from 0.44097 to 0.34323, saving model to Res

KeyboardInterrupt: 

In [17]:
from keras.callbacks import EarlyStopping,ModelCheckpoint,ReduceLROnPlateau

# early_stopping : val_loss 連續不降低時，結束訓練
early_stopping = EarlyStopping(monitor='val_loss', patience=15, verbose=1,restore_best_weights=True,mode='auto')
# reduce_lr : val_loss 連續不降低時，減少learning rate
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, verbose=1, mode='auto',
                            epsilon=0.0001, cooldown=0, min_lr=0)

checkpoint = ModelCheckpoint('Mobile_messy_small_v1.h5', monitor='val_loss', verbose=1,
    save_best_only=True, mode='auto', period=1)

model = MobileNet(input_shape = (128, 128, 3), weights=None, classes=class_num)


model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         (None, 128, 128, 3)       0         
_________________________________________________________________
conv1_pad (ZeroPadding2D)    (None, 129, 129, 3)       0         
_________________________________________________________________
conv1 (Conv2D)               (None, 64, 64, 32)        864       
_________________________________________________________________
conv1_bn (BatchNormalization (None, 64, 64, 32)        128       
_________________________________________________________________
conv1_relu (ReLU)            (None, 64, 64, 32)        0         
_________________________________________________________________
conv_dw_1 (DepthwiseConv2D)  (None, 64, 64, 32)        288       
_________________________________________________________________
conv_dw_1_bn (BatchNormaliza (None, 64, 64, 32)        128       
__________

In [18]:
optimizer = keras.optimizers.Adam(lr=0.0001)
model.compile(optimizer=optimizer, loss="categorical_crossentropy", metrics=["accuracy"])
history = model.fit(x=X_train, y=Y_train, validation_data=(X_valid, Y_valid), epochs=50, batch_size = 32, callbacks=[early_stopping,checkpoint,reduce_lr])
        
# complete_time=time.strftime("%Y_%m_%d %H_%M_%S", time.localtime()) 
# model.save('MobileNet_'+str(complete_time)+'.h5')

Train on 2320 samples, validate on 93 samples
Epoch 1/50
2320/2320 [==============================] - 245s 106ms/step - loss: 1.1287 - acc: 0.3647 - val_loss: 1.1014 - val_acc: 0.3548

Epoch 00001: val_loss improved from inf to 1.10143, saving model to Mobile_messy_small_v1.h5
Epoch 2/50
2320/2320 [==============================] - 233s 101ms/step - loss: 1.0866 - acc: 0.3978 - val_loss: 1.2853 - val_acc: 0.3441

Epoch 00002: val_loss did not improve from 1.10143
Epoch 3/50
2320/2320 [==============================] - 235s 101ms/step - loss: 1.0563 - acc: 0.4466 - val_loss: 1.2328 - val_acc: 0.3548

Epoch 00003: val_loss did not improve from 1.10143
Epoch 4/50
2320/2320 [==============================] - 234s 101ms/step - loss: 1.0291 - acc: 0.4603 - val_loss: 1.2707 - val_acc: 0.3226

Epoch 00004: val_loss did not improve from 1.10143

Epoch 00004: ReduceLROnPlateau reducing learning rate to 4.999999873689376e-05.
Epoch 5/50
2320/2320 [==============================] - 233s 101ms/step

KeyboardInterrupt: 

In [9]:
print(Y_train[:200])

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1.

In [10]:
from keras import models
name='ResNet50_prepro_v2.h5'
model = models.load_model(name)
model.predict(X_train[0:100])

array([[1.00000000e+00, 5.66422777e-12, 5.62605562e-09],
       [4.72342799e-06, 9.99995232e-01, 5.44019994e-12],
       [2.22079652e-05, 9.99977827e-01, 9.97252766e-11],
       [4.50656917e-05, 9.99927282e-01, 2.77058170e-05],
       [9.99998450e-01, 4.87083511e-08, 1.56183000e-06],
       [9.99552548e-01, 5.20305150e-07, 4.46972932e-04],
       [9.99999762e-01, 1.56490927e-08, 2.16029051e-07],
       [8.46422699e-05, 1.03078319e-05, 9.99904990e-01],
       [1.00000000e+00, 1.46851797e-09, 1.81734916e-09],
       [2.28786885e-05, 9.99976993e-01, 7.14348971e-08],
       [1.00000000e+00, 1.67456451e-10, 5.73602110e-10],
       [9.51505281e-05, 1.07565589e-04, 9.99797285e-01],
       [4.42364981e-05, 9.99955773e-01, 4.38239792e-11],
       [1.00000000e+00, 2.14241125e-12, 1.19152726e-11],
       [2.64672108e-05, 9.99973536e-01, 5.85306673e-12],
       [9.55391297e-05, 1.69427833e-04, 9.99735057e-01],
       [4.54128931e-05, 9.99936461e-01, 1.80694115e-05],
       [1.00000000e+00, 4.78781