In [1]:
import os
import time
import tensorflow as tf
import scipy.io as sio 
from keras.applications.resnet50 import ResNet50
from keras.applications.mobilenet import MobileNet
import keras


c:\Users\USER\anaconda3\envs\MNIST\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\Users\USER\anaconda3\envs\MNIST\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\Users\USER\anaconda3\envs\MNIST\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\Users\USER\anaconda3\envs\MNIST\lib\site-packages\tensorflow\python\frame

In [2]:

def one_hot_matrix(labels, C):
    
    ### START CODE HERE ###
    
    # Create a tf.constant equal to C (depth), name it 'C'.
    depth = tf.constant(C, name = "C")
    
    # Use tf.one_hot, be careful with the axis (approx. 1 line)
    one_hot_matrix = tf.one_hot(labels, depth, axis=0)
    
    # Create the session
    sess = tf.Session()
    
    # Run the session
    one_hot = sess.run(one_hot_matrix)
    
    # Close the session.
    sess.close() 
    
    return one_hot

In [3]:
from sklearn.utils import shuffle
file_path = os.getcwd() + '\\train'
label_name = os.listdir(file_path)
class_num = 6

matfn='train_messy_6.mat' 
data=sio.loadmat(matfn) 


X_train = data['X_data'] 
X_train = X_train / 255
Y_train = data['Y_data']
# Y_train = Y_train.T

# X_train, Y_train = shuffle(X_train, Y_train)



"""
X_val = X_train[4200:]
Y_val = Y_train[4200:]

X_train = X_train[:4200]
Y_train = Y_train[:4200]
"""

print(X_train.shape)
print(Y_train.shape)

(4795, 224, 224, 3)
(1, 4795)


In [4]:
data_num = X_train.shape[0] 
Y_train = one_hot_matrix(Y_train, class_num)
Y_train = Y_train.T
Y_train = Y_train.reshape(data_num, class_num)
print(Y_train.shape)

(4795, 6)


In [5]:
print(Y_train)
print(Y_train.shape)

[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]
(4795, 6)


In [6]:
import random
num_examples = X_train.shape[0]
index_list = list(range(num_examples))
random.shuffle(index_list)

# 根据打乱后的索引重新排列训练数据和标签
X_train = X_train[index_list]
Y_train = Y_train[index_list]

In [7]:
print(Y_train[500:600])
print(Y_train.shape)

[[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0.

In [8]:
from keras.callbacks import EarlyStopping,ModelCheckpoint,ReduceLROnPlateau

# early_stopping : val_loss 連續不降低時，結束訓練
early_stopping = EarlyStopping(monitor='val_loss', patience=15, verbose=1,restore_best_weights=True,mode='auto')
# reduce_lr : val_loss 連續不降低時，減少learning rate
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, verbose=1, mode='auto',
                            epsilon=0.0001, cooldown=0, min_lr=0)

checkpoint = ModelCheckpoint('ResNet50_messy6_v2.h5', monitor='val_loss', verbose=1,
    save_best_only=True, mode='auto', period=1)

pre_model = ResNet50(input_shape = (224, 224, 3), weights='imagenet')
transfer_model = keras.models.Sequential()
transfer_model.add(pre_model)
# transfer_model.add(keras.layers.Flatten())
transfer_model.add(keras.layers.Dense(1024, activation='relu'))
transfer_model.add(keras.layers.Dense(1024, activation='relu'))
transfer_model.add(keras.layers.Dense(512, activation='relu'))
transfer_model.add(keras.layers.Dense(512, activation='relu'))
transfer_model.add(keras.layers.Dropout(0.5))
transfer_model.add(keras.layers.Dense(256, activation='relu'))
transfer_model.add(keras.layers.Dense(256, activation='relu'))
transfer_model.add(keras.layers.Dense(128, activation='relu'))
transfer_model.add(keras.layers.Dense(128, activation='relu'))
transfer_model.add(keras.layers.Dropout(0.5))
transfer_model.add(keras.layers.Dense(64, activation='relu'))
transfer_model.add(keras.layers.Dense(64, activation='relu'))
transfer_model.add(keras.layers.Dense(6, activation='softmax'))



transfer_model.summary()

Instructions for updating:
Colocations handled automatically by placer.


c:\Users\USER\anaconda3\envs\MNIST\lib\site-packages\keras\callbacks.py:1065: UserWarning: `epsilon` argument is deprecated and will be removed, use `min_delta` instead.
  warnings.warn('`epsilon` argument is deprecated and '


Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
resnet50 (Model)             (None, 1000)              25636712  
_________________________________________________________________
dense_1 (Dense)              (None, 1024)              1025024   
_________________________________________________________________
dense_2 (Dense)              (None, 1024)              1049600   
_________________________________________________________________
dense_3 (Dense)              (None, 512)               524800    
_________________________________________________________________
dense_4 (Dense)              (None, 512)               262656    
_________________________________________________________________
dropout_1 (Dropout)          (None, 512)               0         
___________________________

In [9]:
optimizer = keras.optimizers.Adam(lr=0.0001)
transfer_model.compile(optimizer=optimizer, loss="categorical_crossentropy", metrics=["accuracy"])
history = transfer_model.fit(x=X_train, y=Y_train, validation_split = 0.2, epochs=50, batch_size = 64, callbacks=[early_stopping,checkpoint,reduce_lr])
        
# complete_time=time.strftime("%Y_%m_%d %H_%M_%S", time.localtime()) 
# model.save('MobileNet_'+str(complete_time)+'.h5')

Instructions for updating:
Use tf.cast instead.
Train on 3836 samples, validate on 959 samples
Epoch 1/50
3836/3836 [==============================] - 997s 260ms/step - loss: 1.7621 - acc: 0.2200 - val_loss: 1.5845 - val_acc: 0.3264

Epoch 00001: val_loss improved from inf to 1.58448, saving model to ResNet50_messy6_v2.h5
Epoch 2/50
3836/3836 [==============================] - 989s 258ms/step - loss: 1.5763 - acc: 0.3321 - val_loss: 2.3574 - val_acc: 0.2649

Epoch 00002: val_loss did not improve from 1.58448
Epoch 3/50
3836/3836 [==============================] - 993s 259ms/step - loss: 1.5118 - acc: 0.3595 - val_loss: 1.4756 - val_acc: 0.3410

Epoch 00003: val_loss improved from 1.58448 to 1.47556, saving model to ResNet50_messy6_v2.h5
Epoch 4/50
3836/3836 [==============================] - 995s 259ms/step - loss: 1.2022 - acc: 0.4150 - val_loss: 0.9989 - val_acc: 0.4818

Epoch 00004: val_loss improved from 1.47556 to 0.99888, saving model to ResNet50_messy6_v2.h5
Epoch 5/50
3836/3836

KeyboardInterrupt: 

In [ ]:
print(Y_train[:200])

In [ ]:
from keras import models
name='ResNet50_prepro_v2.h5'
model = models.load_model(name)
model.predict(X_train[0:100])