In [1]:
import os
import time
import tensorflow as tf
import scipy.io as sio 
from keras.applications.resnet50 import ResNet50
from keras.applications.mobilenet import MobileNet


C:\Users\USER\anaconda3\envs\MNIST\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\USER\anaconda3\envs\MNIST\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\USER\anaconda3\envs\MNIST\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\USER\anaconda3\envs\MNIST\lib\site-packages\tensorflow\python\frame

In [2]:

def one_hot_matrix(labels, C):
    
    ### START CODE HERE ###
    
    # Create a tf.constant equal to C (depth), name it 'C'.
    depth = tf.constant(C, name = "C")
    
    # Use tf.one_hot, be careful with the axis (approx. 1 line)
    one_hot_matrix = tf.one_hot(labels, depth, axis=0)
    
    # Create the session
    sess = tf.Session()
    
    # Run the session
    one_hot = sess.run(one_hot_matrix)
    
    # Close the session.
    sess.close() 
    
    return one_hot

In [3]:
from sklearn.utils import shuffle
file_path = os.getcwd() + '\\train'
label_name = os.listdir(file_path)
class_num = 3

matfn='data_preprocessed_v3.mat' 
data=sio.loadmat(matfn) 


X_train = data['X_data'] 
X_train = X_train / 255
Y_train = data['Y_data']
# Y_train = Y_train.T

# X_train, Y_train = shuffle(X_train, Y_train)



"""
X_val = X_train[4200:]
Y_val = Y_train[4200:]

X_train = X_train[:4200]
Y_train = Y_train[:4200]
"""

print(X_train.shape)
print(Y_train.shape)

(6000, 224, 224, 3)
(1, 6000)


In [4]:
data_num = X_train.shape[0] 
Y_train = one_hot_matrix(Y_train, class_num)
Y_train = Y_train.T
Y_train = Y_train.reshape(data_num, class_num)
print(Y_train.shape)

(6000, 3)


In [5]:
print(Y_train)
print(Y_train.shape)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 ...
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
(6000, 3)


In [6]:
import random
num_examples = X_train.shape[0]
index_list = list(range(num_examples))
random.shuffle(index_list)

# 根据打乱后的索引重新排列训练数据和标签
X_train = X_train[index_list]
Y_train = Y_train[index_list]

In [7]:
print(Y_train[0:200])

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1.

In [8]:
from keras.callbacks import EarlyStopping,ModelCheckpoint,ReduceLROnPlateau

# early_stopping : val_loss 連續不降低時，結束訓練
early_stopping = EarlyStopping(monitor='val_loss', patience=15, verbose=1,restore_best_weights=True,mode='auto')
# reduce_lr : val_loss 連續不降低時，減少learning rate
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, verbose=1, mode='auto',
                            epsilon=0.0001, cooldown=0, min_lr=0)

checkpoint = ModelCheckpoint('ResNet50_prepro_v2.h5', monitor='val_loss', verbose=1,
    save_best_only=True, mode='auto', period=1)

model = ResNet50(input_shape = (224, 224, 3), weights=None, classes=class_num)
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])
history = model.fit(x=X_train, y=Y_train, validation_split=0.1, epochs=50, batch_size = 64, callbacks=[early_stopping,checkpoint,reduce_lr])

complete_time=time.strftime("%Y_%m_%d %H_%M_%S", time.localtime()) 
# model.save('MobileNet_'+str(complete_time)+'.h5')


Instructions for updating:
Colocations handled automatically by placer.


C:\Users\USER\anaconda3\envs\MNIST\lib\site-packages\keras\callbacks.py:1065: UserWarning: `epsilon` argument is deprecated and will be removed, use `min_delta` instead.
  warnings.warn('`epsilon` argument is deprecated and '


Instructions for updating:
Use tf.cast instead.
Train on 5400 samples, validate on 600 samples
Epoch 1/50
5400/5400 [==============================] - 2416s 447ms/step - loss: 0.8740 - acc: 0.6559 - val_loss: 3.8410 - val_acc: 0.4817

Epoch 00001: val_loss improved from inf to 3.84103, saving model to ResNet50_prepro_v2.h5
Epoch 2/50
5400/5400 [==============================] - 2411s 446ms/step - loss: 0.1046 - acc: 0.9631 - val_loss: 10.1821 - val_acc: 0.3667

Epoch 00002: val_loss did not improve from 3.84103
Epoch 3/50
5400/5400 [==============================] - 2405s 445ms/step - loss: 0.0601 - acc: 0.9798 - val_loss: 10.2081 - val_acc: 0.3667

Epoch 00003: val_loss did not improve from 3.84103
Epoch 4/50
5400/5400 [==============================] - 2408s 446ms/step - loss: 0.0395 - acc: 0.9880 - val_loss: 10.2081 - val_acc: 0.3667

Epoch 00004: val_loss did not improve from 3.84103

Epoch 00004: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
Epoch 5/50
5400/54

KeyboardInterrupt: 

In [9]:
print(Y_train[:200])

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1.

In [10]:
from keras import models
name='ResNet50_prepro_v2.h5'
model = models.load_model(name)
model.predict(X_train[0:100])

array([[1.00000000e+00, 5.66422777e-12, 5.62605562e-09],
       [4.72342799e-06, 9.99995232e-01, 5.44019994e-12],
       [2.22079652e-05, 9.99977827e-01, 9.97252766e-11],
       [4.50656917e-05, 9.99927282e-01, 2.77058170e-05],
       [9.99998450e-01, 4.87083511e-08, 1.56183000e-06],
       [9.99552548e-01, 5.20305150e-07, 4.46972932e-04],
       [9.99999762e-01, 1.56490927e-08, 2.16029051e-07],
       [8.46422699e-05, 1.03078319e-05, 9.99904990e-01],
       [1.00000000e+00, 1.46851797e-09, 1.81734916e-09],
       [2.28786885e-05, 9.99976993e-01, 7.14348971e-08],
       [1.00000000e+00, 1.67456451e-10, 5.73602110e-10],
       [9.51505281e-05, 1.07565589e-04, 9.99797285e-01],
       [4.42364981e-05, 9.99955773e-01, 4.38239792e-11],
       [1.00000000e+00, 2.14241125e-12, 1.19152726e-11],
       [2.64672108e-05, 9.99973536e-01, 5.85306673e-12],
       [9.55391297e-05, 1.69427833e-04, 9.99735057e-01],
       [4.54128931e-05, 9.99936461e-01, 1.80694115e-05],
       [1.00000000e+00, 4.78781